name: cargoquintest
description: "Este proyecto formó parte del proceso de aplicación para la vacante de desarrollador movil con grupo CQ/3PL"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^3.0.3
  go_router: ^17.0.0
  intl: ^0.20.2
  uuid: ^4.5.2
  nb_utils: ^7.1.8


dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.1
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter_icons:
  android: true
  ios: true
  image_path: lib/assets/logos/cq-logo.png
  adaptive_icon_background: "#FFFFFF"
  remove_alpha_ios: true

flutter_native_splash:
  color: "#FFFFFF"
  color_dark: "#0E0E0E"
  image: lib/assets/logos/cq-logo.png
  android_12:
    icon_background_color: "#FFFFFF"
    image: lib/assets/logos/cq-logo.png
    image_dark: lib/assets/logos/cq-logo.png
  web: false

flutter:

  uses-material-design: true

  #assets:
  #- images/a_dot_burr.jpeg
  #- images/a_dot_ham.jpeg

  #fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
